<foutmelding><context>Fout tijdens controleren precondities.</context><stacktrace>nl.bzk.migratiebrp.conversie.model.exceptions.OngeldigeAutorisatieException
	at nl.bzk.migratiebrp.conversie.regels.proces.preconditie.PreconditiesService.verwerk(PreconditiesService.java:125)
	at nl.bzk.migratiebrp.test.autorisatie.ConversieTestCasus.testPrecondities(ConversieTestCasus.java:226)
	at nl.bzk.migratiebrp.test.autorisatie.ConversieTestCasus.run(ConversieTestCasus.java:111)
	at nl.bzk.migratiebrp.test.dal.runner.TestRunner.runTest(TestRunner.java:117)
	at nl.bzk.migratiebrp.test.dal.runner.TestRunner.run(TestRunner.java:103)
	at nl.bzk.migratiebrp.test.dal.runner.TestRunner.run(TestRunner.java:107)
	at nl.bzk.migratiebrp.test.dal.runner.TestRunner.run(TestRunner.java:94)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
</stacktrace></foutmelding>